{% set name = "robocorp-log" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_log-{{ version }}.tar.gz
  sha256: 4cf371c13b5b31dbfefa20504012c2eb684065b1c02182b0798bd9f91998c8b1

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9.0,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - tomli >=2.0.1,<3.0.0
    - psutil >=5.9.0,<6.0.0

test:
  imports:
    - robocorp.log
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Automatic trace logging for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
